### ISSUE TITLE
README.md doesn’t say that it’s a Lean verifier

### ISSUE THREAD

**Issue by girving** [ammkrn/nanoda_lib#2]
The README is only about the internal implementation (which is cool!), but doesn’t say what the project does.  It would be nice to have a few sentence section saying it’s for independently checking Lean proofs.

**Comment by ammkrn** [comment]
Touché. I'm going to leave this open for a short time; there's a rewrite in the works to make some big simplifications, get rid of the macros, and remove the integer indirection. I'll overhaul the README when that goes up.

**Comment by ammkrn** [comment]
@girving As part of an overhaul to get in all of the Lean 4 changes, the README has been updated to be more descriptive. It also links to a [separate book](https://ammkrn.github.io/type_checking_in_lean4/) all about type checking and exporting for Lean 4 which covers things in more depth.

Feel free to re-open this or file a separate PR if you have additional input.

**Comment by girving** [comment]
Thank you!  Though I’ll note that the README for the book on GitHub doesn’t link to the book’s website. :)

**Comment by ammkrn** [comment]
Fixed, good eye.
